[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-aether_os.json"

[target.x86_64-aether_os]
linker = "rust-lld"
rustflags = [
  "-C", "link-args=-nostdlib",
]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"